/**
 * useGitHubData Hook
 * 
 * Merges auto-synced GitHub metadata (stars, forks, language, last updated)
 * with the existing project data from projectsData.js.
 * 
 * The data source is src/data/githubData.json, generated by scripts/sync-github.js.
 */

import { useMemo } from 'react';

let githubData = { repos: {}, newRepos: [] };
try {
  githubData = require('../data/githubData.json');
} catch {
  // githubData.json doesn't exist yet — that's fine
}

/**
 * Parse a GitHub URL to get the "owner/repo" slug (lowercase).
 */
function toSlug(githubUrl) {
  if (!githubUrl || githubUrl === '#') return null;
  const match = githubUrl.match(/github\.com\/([^/]+)\/([^/#?]+)/);
  return match ? `${match[1]}/${match[2]}`.toLowerCase() : null;
}

/**
 * Get GitHub metadata for a single project by its githubUrl.
 * Returns null if no data is available.
 */
export function getGitHubStats(githubUrl) {
  const slug = toSlug(githubUrl);
  if (!slug || !githubData.repos) return null;
  return githubData.repos[slug] || null;
}

/**
 * Hook: returns projects enriched with GitHub stats.
 * Each project gets a `.github` property with:
 *   { stars, forks, language, updatedAt, pushedAt, topics, license, openIssues }
 * 
 * Usage:
 *   const enrichedProjects = useGitHubProjects(portfolioData.projects);
 */
export function useGitHubProjects(projects) {
  return useMemo(() => {
    if (!projects) return [];
    return projects.map(project => {
      const stats = getGitHubStats(project.githubUrl);
      return stats
        ? { ...project, github: stats }
        : project;
    });
  }, [projects]);
}

/**
 * Get the list of new repos detected on GitHub that are NOT in projectsData.
 */
export function getNewRepos() {
  return githubData.newRepos || [];
}

/**
 * Get the timestamp when the GitHub data was last synced.
 */
export function getLastSyncTime() {
  return githubData._generated || null;
}

export default useGitHubProjects;
